### PR TITLE
Create config.cfg

### PR DESCRIPTION
**Pull request by sn1ce**
config-file without "infos"

### CODE REVIEW

**Comment by jammsen** [comment]
I rather would have a descriptive config file as a beginner hosting TheForest with all that weird configstuff, than have no info whatsoever.

**Comment by jammsen** [comment]
Also i just generated a new config file, from a fresh test-server and compared that to my example, its still good.

**Comment by jammsen** [comment]
Why would you want to remove descriptions?

**Comment by sn1ce** [comment]
Haha, from my sight - nearly all already says what it is, I always doing it like this :-) 

So completely fine

**Comment by jammsen** [comment]
Thanks for your contribution, but im gonna leave if for now like it is, its easier for beginners that way.

**Pull request closed without merging**
